### ISSUE TITLE
Usage of exit

### ISSUE THREAD

**Issue by peter-toft-greve** [mborgerding/kissfft#49]
Hi all

For embedded usage - NXP i.MX8 - I have problems with usage of exit(). We do not have it :-(
Would you be fine by having a pull request where exit() is wrapped into a macro - where every exit() becomes KISSFFT_EXIT()

```
#ifdef KISSFFTT_NO_EXIT 
#define KISSFFT_EXIT {}
#else 
#define KISSFFT_EXIT exit
#endif 
```

**Comment by mborgerding** [comment]
I'm curious. What do you do to signal errors on such a platform?

**Comment by peter-toft-greve** [comment]
I don't think we can :-(
Survive and make sure that there are no goofs in parameter setups etc.

It is quite common on low end platforms that you do not get exit() control nor printf()

**Comment by mborgerding** [comment]
OK, I see. I'm guessing you are talking about the exit calls in `tools/kiss_fftr.c`.  That is all I could find outside test code.
Blech. Yech.  I don't like them.  Exiting from library code is not good. I think it'd be better to simply return rather than exit.

If you want to make such a PR, go for it.  If I don't hear back from you soon, I'll go ahead and change those `exit(1)` -> `return`.

**Comment by peter-toft-greve** [comment]
Cool - actually I prefer you patch it in the style you like. I trust you here :)
I can surely review if you like.

**Comment by peter-toft-greve** [comment]
Brilliant!
